name: classshare
description: "Projeto acadêmico para organizar e compartilhar fotos por sala/disciplina."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Banco de dados local
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Seleção de imagens
  image_picker: ^1.0.7

  # Compartilhamento nativo do SO
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Geração automática de launcher icons
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#1565C0"
  adaptive_icon_foreground: "assets/icon/icon.png"
